# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - 3.6
install: pip install -r requirements.txt

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app.py"
  - export FLASK_DEBUG=1
  - export DATABASE_URL='sqlite:///wishtree.db'
  - python "$TRAVIS_BUILD_DIR/app.py"

script: python "$TRAVIS_BUILD_DIR/test.py"

deploy:
  - provider: elasticbeanstalk
    access_key_id: AKIAJAVFKERWW254CLLA
    secret_access_key: $AWS_SECRET_KEY
    app: wishtree
    env: Wishtree-env
    bucket_name: wishtree
    skip_cleanup: true
